version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - recipestaticdata:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipedb
      - DB_USER=recipeuser
      - DB_PASS=2001200198
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - recipedbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipedb
      - POSTGRES_USER=recipeuser
      - POSTGRES_PASSWORD=2001200198

volumes:
  recipedbdata:
  recipestaticdata:

